### ISSUE TITLE
Please provide a `flake.nix`

### ISSUE THREAD

**Issue by NobbZ** [nix-community/trustix#14]
**Is your feature request related to a problem? Please describe.**

The current installation instructions assume that a local clone of the repository can be made and easily accessed through an absolute path.

This is not possible in flakes, also it is barely reproducible to keep a user maintained clone around.

**Describe the solution you'd like**

Provide a `flake.nix` file that declares the important outputs and makes them available to consuming flakes.

**Describe alternatives you've considered**

Using "trustix" as a `flake = false` input.

**Comment by NobbZ** [comment]
Just realising, this will be closed by #9.

**Comment by adisbladis** [comment]
Closed by 4043f7b3f39fdb6d3bfcfcd53c1af6e9ab5a31b4.
