### ISSUE TITLE
Complete LUA -> JS transition

### ISSUE THREAD

**Issue by davidak** [nix-community/trustix#44]
**Describe the bug**

There is still LUA in the code:

```
[davidak@gaming:~/code/trustix]$ grep lua -R .
...
./packages/trustix-nix/gomod2nix.toml:["github.com/Shopify/go-lua"]
./packages/trustix-nix/gomod2nix.toml:  ["github.com/Shopify/go-lua".fetch]
./packages/trustix-nix/gomod2nix.toml:    url = "https://github.com/Shopify/go-lua"
```

Related:

- https://github.com/tweag/trustix/issues/13
- https://github.com/tweag/trustix/commit/f4e0241b837b9a090af2e59953f3fdef350a3a16

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
 - OS name + version:
 - Version of the code:

**Additional context**

**Comment by adisbladis** [comment]
This is now gone.
