### ISSUE TITLE
NixOS Reproducibility Community Dashboard

### ISSUE THREAD

**Issue by davidak** [nix-community/trustix#47]
There seem to be work started for something like that in [trustix-nix-reprod](https://github.com/tweag/trustix/tree/master/packages/trustix-nix-reprod). It would be great to have a dashboard and documented workflow how one can contribute to it.

Multiple people from https://matrix.to/#/#reproducible-builds:nixos.org are running the r13y tests themselves. It would be great to spread the work better and get a more robust result if different people run the tests on different systems.

Can you finish this project, so NixOS can host the dashboard? Maybe the foundation can sponsor the development.

**Comment by adisbladis** [comment]
Documentation for how to contribute to a community dashboard needs to go in the 1.0 release docs.

**Comment by adisbladis** [comment]
https://r13y.trustix.dev is now deployed. While no means final I think we can close this issue.
