### ISSUE TITLE
Reward becoming a builder

### ISSUE THREAD

**Issue by mahdi-ln** [nix-community/trustix#67]
Trustix clients should pay small amount in every connection (through a privacycoins). becoming a builder should be rewarded by these money. Without incentive there is no decentralization

**Comment by mahdi-ln** [comment]
However I prefer [this alternative](https://github.com/nix-community/trustix/issues/66) as I already should pay for a incentivized multi layer anonymizing proxy (Lokinet)

**Comment by davidak** [comment]
This is a community project and not something to profit from. Also, adding payment would make it less accessible.

**Comment by adisbladis** [comment]
This is expressly something Trustix was designed _not_  to do. 
I think the financial incentives do not make sense for us.

You could trivially create a platform to tip builders without involving cryptocurrencies. Is this something you have considered?
