### ISSUE TITLE
A proof-of-work blockchain for "binary transparency" and "data transparency"

### ISSUE THREAD

**Issue by mahdi-ln** [nix-community/trustix#71]
I was thinking of an international proof-of-work blockchain for "binary transparency" and "data transparency". (data/content-transparency can be used in decentralized web projects like ZeroNet)
In proof-of-work blockchain, can remain immune to split-view-attack because client can independently verify the difficulty of the blockchain so it can assure it is seeing an international powerful blockchain.
**Who pays for Miners?**
While writing to this blockchain can be free they can also be a donation wallet used for rewarding miners. Those you care not to become victim of split-view attack can donate to this wallet.

Notes:
1.I'm not expert
2.it can be in combination of your multi-signature approach

**Comment by mahdi-ln** [comment]
Update 1:
Who pays for Miners?
While writing to this blockchain can be free they can also be a donation wallet used for rewarding miners. Those you care not to become victim of split-view attack can donate to this wallet.

Update 2:
it can be in combination of your multi-signature approach

**Comment by davidak** [comment]
I don't think we need such a blockchain.

**Comment by adisbladis** [comment]
Closing for similar reasons as https://github.com/nix-community/trustix/issues/67#issuecomment-1283376388.
