### ISSUE TITLE
Create unopinionated docs

### ISSUE THREAD

**Issue by davidak** [nix-community/trustix#87]
Currently, this page uses Colmena for deployment. There are many deployment tools and users don't know which to use. This is a huge issue! The docs should be for plain NixOS, so users can adapt it to any tools they might use.

https://nix-community.github.io/trustix/howto-nix/colmena/index.html

@adisbladis If you agree, i can create a PR.

**Comment by adisbladis** [comment]
Colmena deployment removed from docs in deec2012242f9b668558f40c86c9fab4864edc24 and a simpler implementation is used.

The reason I used a deployment tool was to get secrets management, but I think it's better to just use store paths even though they are world readable, and document that this is bad practice and refer to tools like sops-nix for how to really deal with secrets.
